### ISSUE TITLE
フロントエンド（Next.js, ChakuraUI）のセットアップ

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/mono-auction-interface#1]
### フレームワークを追加
- Next.js
- wagmi
- ChakraUI
のセットアップ

### ディレクトリを追加
- components UIコンポーネントをおく場所
- hooks カスタムhooksをおく場所

**Comment by yuki-o1o5** [comment]
担当します！

**Comment by yu23ki14** [comment]
wagmiはべつissue
