### ISSUE TITLE
wagmi のセットアップ

### ISSUE THREAD

**Issue by geeknees** [henkaku-center/mono-auction-interface#6]
https://github.com/henkaku-center/mono-auction-interface/issues/1 からの切り出し

https://wagmi.sh/core/getting-started

**Comment by yawn-c111** [comment]
@yu23ki14 @geeknees 
こちら私が挑戦してみてもいいでしょうか？🙌

作業内容としては、
- wagmi のドキュメントに沿って `createClient` を準備
- providers.tsx 内で、一番外側に `<WagmiConfig>` を配置

という流れで大丈夫でしょうか？
